[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run db:generate --prefix server"
]

[start]
cmd = "npm run db:migrate --prefix server && node server/src/index.js"
